name: Linters

on:
    push:
        branches: "**"

jobs:
    per-commit:
        runs-on: ubuntu-latest

        steps:
            - name: Setup environment
              run: uv sync --frozen
            
            - name: ruff format
              run: uv run ruff format